name: airline_lakehouse
version: "0.1.0"
config-version: 2
profile: airline_lakehouse

model-paths: ["models"]
test-paths: ["tests"]

vars:
  # Directory holding the silver Parquet datasets written by pipeline/ (Spark or DuckDB).
  silver_path: "../data/silver"

models:
  airline_lakehouse:
    staging:
      +materialized: view
    core:
      +materialized: table
    marts:
      +materialized: table
